### ISSUE TITLE
Silex 2 version

### ISSUE THREAD

**Issue by mvanbaak** [saxulum/saxulum-webprofiler-provider#2]

**Comment by dominikzogg** [comment]
@mvanbaak please try: "saxulum/saxulum-webprofiler-provider": "2.0@dev"

**Comment by mvanbaak** [comment]
You forgot to change the ServiceProvider usage in 'src/Provider/SaxulumWebProfilerProvider.php'

This is now in Pimple instead of Silex:
"Providers must implement the Pimple\ServiceProviderInterface:"

**Comment by dominikzogg** [comment]
of updated it

**Comment by mvanbaak** [comment]
Works! Thanks a lot!

**Comment by mvanbaak** [comment]
I dont have time right now, but all that's missing in my opinion is an update to the README and you are good to go to tag 2.0 ;-) Thanks a lot for your work.

**Comment by dominikzogg** [comment]
@mvanbaak done
